apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch
  namespace: filebeat
data:
  host: {{ .Values.elasticsearch.host | default "" | quote }}
  port: {{ .Values.elasticsearch.port | default "9200" | quote }}
  username: {{ .Values.elasticsearch.username | default "elastic" | quote }}