---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: elasticsearch
  namespace: filebeat
stringData:
  password: {{ .Values.elasticsearch.password | default "" | quote }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: elastic-cloud
  namespace: filebeat
stringData:
  id: {{ .Values.elastic.cloud.id | default "" | quote }}
  auth: "{{ .Values.elasticsearch.username }}:{{ .Values.elasticsearch.password }}"