service: ted-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events:
     - http: GET /hello
  squared:
    handler: handler.squaredNum
    events:
     - http: GET /squared
  shopping:
    handler: handler.shoppingList
    events:
     - http: POST /List
package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
  include:
    - handler.py

plugins:
  - serverless-python-requirements
